dist: xenial   # required for Python >= 3.7
language: python
# python versions to use during the tests
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - mypy network_simulator/
  - pytest --cov-report term-missing --cov=network_simulator/
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - localhost@zspatter.dev
    on_success: change
    on_failure: always
