dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
install:
  - pip install networkx
  - pip install matplotlib
  - pip install mypy
script:
  - pytest
